#! /bin/bash

mkdir -p ~/collections

echo "
events { worker_connections 1024; }

http {
    client_max_body_size 8192M;

    server {
        listen 80;
        location /webdav/ {
            proxy_pass         $WORKSPACE_URL;
            proxy_redirect     off;
            proxy_set_header   Cookie JSESSIONID=$SESSION_ID;
        }
    }
}
" > ~/.nginx.conf

sudo nginx -c ~/.nginx.conf
mkdir /home/jovyan/coll
chmod 600 ~/.davfs2/secrets
chmod a-s ~/.davfs2/cache/localhost-webdav-v1+home-jovyan-coll+jovyan
echo /home/jovyan/coll dummyuser dummypassword > ~/.davfs2/secrets
mount /home/jovyan/coll
wdfs http://localhost/webdav/v1/ ~/collections/ & jupyter-labhub
