#! /bin/bash

echo "
events { worker_connections 1024; }

http {
    client_max_body_size 8192M;

    server {
        listen 80;
        location /webdav/ {
            proxy_pass         $WORKSPACE_URL;
            proxy_redirect     off;
            proxy_set_header   Cookie JSESSIONID=$SESSION_ID;
        }
    }
}
" > ~/.nginx.conf

sudo nginx -c ~/.nginx.conf

mkdir ~/collections
mkdir -p ~/.davfs2/cache/localhost-webdav-v1+home-jovyan-collections+jovyan
chmod 700 ~/.davfs2/cache/localhost-webdav-v1+home-jovyan-collections+jovyan
chmod a-s ~/.davfs2/cache/localhost-webdav-v1+home-jovyan-collections+jovyan
echo "
delay_upload    0
ask_auth        0
use_locks       0
" > ~/.davfs2/davfs2.conf
touch ~/.davfs2/secrets
chmod 600 ~/.davfs2/secrets

mount ~/collections

jupyter-labhub
