#! /bin/bash

mkdir -p ~/collections

echo "
events { worker_connections 1024; }

http {
    client_max_body_size 8192M;

    server {
        listen 80;
        location /webdav/ {
            proxy_pass         $WORKSPACE_URL;
            proxy_redirect     off;
            proxy_set_header   Cookie JSESSIONID=$SESSION_ID;
        }
    }
}
" > ~/.nginx.conf

sudo nginx -c ~/.nginx.conf
wdfs http://localhost/webdav/ ~/collections/ & jupyter-labhub --config=/config.py
