export const LOCAL_STORAGE_MENU_KEY = 'FAIRSPACE_MENU_EXPANDED';
export const SESSION_STORAGE_METADATA_FILTERS_KEY = 'FAIRSPACE_METADATA_FILTERS';

// UI
export const LEFT_MENU_EXPANSION_DELAY = 500;
export const MAIN_CONTENT_WIDTH = '55%';
export const SIDE_PANEL_WIDTH = '45%';

// Search
export const SEARCH_DEFAULT_SIZE = 10;
