/* eslint-disable no-multi-spaces */

// Metadata
export const UPDATE_METADATA = 'UPDATE_METADATA';
export const UPDATE_METADATA_FULFILLED = UPDATE_METADATA + '_FULFILLED';
export const DELETE_METADATA = 'DELETE_METADATA';
export const DELETE_METADATA_FULFILLED = DELETE_METADATA + '_FULFILLED';

// Vocabulary
export const UPDATE_VOCABULARY = 'UPDATE_VOCABULARY';
export const UPDATE_VOCABULARY_FULFILLED = UPDATE_VOCABULARY + '_FULFILLED';
export const DELETE_VOCABULARY = 'DELETE_VOCABULARY';
export const DELETE_VOCABULARY_FULFILLED = DELETE_VOCABULARY + '_FULFILLED';
