PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
CONSTRUCT {?s rdf:type ?t . ?s rdfs:label ?l}
WHERE {
  { ?s rdf:type ?t FILTER(?t in (%types))}
  OPTIONAL { ?s rdfs:label ?l}
}
