@startuml Fairspace
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

title Context diagram for Fairspace

LAYOUT_WITH_LEGEND()

Person(admin, "Administrator", "An organisation wide administrator for fairspace")
Person(user, "Regular user", "A user without any additional privileges")
Person(datasteward, "Datasteward", "A user appointed to manage the data model")

System_Boundary(fairspace, "Fairspace installation") {
    System(hyperspace, "Hyperspace", "Allows admins to manage workspaces, apps and users")
    System(workspace, "Workspace", "Stores files and associated metadatadata with a configurable model")
    System(jupyterhub, "JupyterHub", "Provides environment for running scripts on the data and metadata in a workspace")
}

System_Ext(irods, "iRODS", "Handles storage of files")

Rel(admin, hyperspace, "Manages workspaces, apps and roles")
Rel(hyperspace, workspace, "Instantiates one or more")
Rel(hyperspace, jupyterhub, "Adds to a workspace")
Rel(jupyterhub, workspace, "Reads files from")
Rel(workspace, irods, "(Optionally) stores files in ")

Rel(user, workspace, "Manages files and metadata")
Rel(datasteward, workspace, "Manages metadata model")

@enduml
