name: Deploy Helm Chart

env:
  HELM_VERSION: '3.14.3'
  HELM_REGISTRY: ghcr.io/${{ github.repository_owner }}/helm-charts
#
## Environment variables available to all jobs and steps in this workflow
#env:
#  GKE_PROJECT: randocats
#  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
#  GITHUB_SHA: ${{ github.sha }}
#  GKE_ZONE: us-east1-b
#  GKE_CLUSTER: randocats-cluster
#  IMAGE: randocats

on:
  push:
    branches:
      - devops/FAIRSPC-23_deployment
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger for Helm chart deploy"
      version:
        description: "Version of the Helm chart to deploy (optional, defaults to latest  snapshot)"
        required: false
      environment:
        description: "Environment to deploy to"
        required: true
        default: "test"
        options:
          - "test"
          - "prod"

jobs:
  setup-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare model and k8s values files
        run: |
          echo "${{ env.FAIRSPACE_VALUES_YAML }}" > fairspace_k8s_values.yaml
          echo "${{ env.FNS_VIEWS_YAML }}" > views.yaml
          echo "${{ env.FNS_VOCABULARY_TTL}}" > vocabulary.ttl
          echo "${{ env.FNS_TAXONOMIES_TTL }}" > taxonomies.ttl

      - name: Define the version
        run: |
          VERSION=$(cat ./VERSION)-SNAPSHOT
          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION=${{ github.event.inputs.version }}
          fi
          echo "Helm charms version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure docker to authenticate
        run: |
          gcloud auth configure-docker

      - name: Setup Helm
        uses: azure/setup-helm@v4.1.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Login with Helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.HELM_REGISTRY }} --username ${{ github.repository_owner }} --password-stdin

      - name: Deploy Helm chart
        run: |
          gcloud container clusters get-credentials fns-cloud-f01 --zone europe-west1-b --project fns-cloud-852306
          helm upgrade --install fairspace oci://${{ env.HELM_REGISTRY }}/fairspace --version ${{ env.VERSION }}
          --namespace=fairspace-${{ github.event.inputs.environment }}
          --set-file saturn.vocabulary=vocabulary.ttl
          --set-file saturn.views=views.yaml
          -f fairspace_k8s_values.yaml

      - name: Clean up
        run: |
          rm -rf fairspace_k8s_values.yaml
          rm -rf vocabulary.ttl
          rm -rf taxonomies.ttl
          rm -rf views.yaml
