# Checks whether an entity exists and not marked as delted yet
#
# 0 - iri
# 1 - graph

PREFIX fs: <http://fairspace.io/ontology#>
PREFIX sh: <http://www.w3.org/ns/shacl#>

ASK WHERE { GRAPH %2$s { %1$s ?p ?o }
  FILTER(NOT EXISTS {GRAPH %2$s { %1$s fs:dateDeleted ?date }})
}