PREFIX fs: <http://fairspace.io/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?iri ?name ?description ?createdBy
WHERE { ?iri a fs:Collection; rdfs:label ?name; rdfs:comment ?description; fs:createdBy ?createdBy; }