# param0 - IRI

PREFIX fs: <http://fairspace.io/ontology#>

# Delete files and folders
INSERT { ?s fs:dateDeleted ?date } WHERE {
?param0 fs:filePath ?collPath;
a fs:Collection.
?s ?p ?o;
fs:filePath ?path .
FILTER(STRSTARTS(?path, CONCAT(?collPath, '/')))
BIND(NOW() as ?date)
};

# Delete the collection
INSERT { ?param0 fs:dateDeleted ?date; }
WHERE { ?param0 a fs:Collection. BIND(NOW() as ?date)};
