# Updates a collection
#
# 0 - IRI
# 1 - name
# 2 - description
# 3 - directory name

PREFIX fs: <http://fairspace.io/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE { ?0 rdfs:label ?name; rdfs:comment ?comment; fs:filePath ?oldPath; }
INSERT { ?0 rdfs:label ?1; rdfs:comment ?2; fs:filePath ?3; }
WHERE { ?0 a fs:Collection; rdfs:label ?name; rdfs:comment ?comment; fs:filePath ?oldPath; BIND(NOW() as ?date) };

# Move the children
DELETE { ?s fs:filePath ?path }
INSERT { ?s fs:filePath ?newPath}
WHERE { ?0 fs:filePath ?oldPath. ?s fs:filePath ?path . FILTER(STRSTARTS(?path, CONCAT(?oldPath, '/')))
BIND(CONCAT(?3, '/', SUBSTR(?path, STRLEN(?oldPath) + 2)) as ?newPath) };