# Creates a collection
#
# param0 - IRI
# param1 - name
# param2 - description
# param3 - creator

PREFIX fs: <http://fairspace.io/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT { ?param0 a fs:Collection; fs:filePath ?param1; fs:fileSize 0; fs:createdBy ?param3; fs:dateCreated ?date; fs:modifiedBy ?param3; fs:dateModified ?date; rdfs:label ?param1; rdfs:comment ?param2 . }
WHERE { BIND(NOW() as ?date) };


