# Updates a collection
#
# param0 - IRI
# param1 - name
# param2 - description


PREFIX fs: <http://fairspace.io/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE { ?param0 rdfs:label ?name; rdfs:comment ?comment; }
INSERT { ?param0 rdfs:label ?param1; rdfs:comment ?param2; }
WHERE { ?param0 a fs:Collection; rdfs:label ?name; rdfs:comment ?comment; BIND(NOW() as ?date) };