# Delete by mask
# 0 - graph
# 1 - subject
# 2 - predicate
# 3 - object

PREFIX fs: <http://fairspace.io/ontology#>

DELETE {GRAPH %1$s {%2$s %3$s %4$s}} WHERE {
    GRAPH %1$s {%2$s %3$s %4$s}
    FILTER NOT EXISTS { GRAPH ws:system-vocabulary { %3$s fs:machineOnly true } }
}
