# Delete by mask
# 0 - graph
# 1 - subject
# 2 - predicate
# 3 - object
# 4 - vocabulary graph

PREFIX fs: <http://fairspace.io/ontology#>

DELETE {GRAPH ?0 {?1 ?2 ?3}} WHERE {
    GRAPH ?0 {?1 ?2 ?3}
    FILTER NOT EXISTS { GRAPH ?4 { ?2 fs:machineOnly true } }
}
