# 0 - graph
# 1 - vocabulary
# 2 - type (optional)

PREFIX fs: <http://fairspace.io/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh: <http://www.w3.org/ns/shacl#>

CONSTRUCT {?s a ?type; rdfs:label ?l}
WHERE {
    GRAPH %1$s { ?s a ?type .  }
    GRAPH %2$s {
      ?type rdfs:subClassOf* %3$s .
      ?shape sh:targetClass ?type .
    }
    OPTIONAL {
        GRAPH %1$s {?s rdfs:label ?l}
    }
}
