# Find a subject violating sh:maxCount constaraint
# 0 - property
# 1 - a list of allowed subject's classes
# 2 - maxCount

SELECT ?subject (count(?object) as ?num)
WHERE {
 ?subject a ?subjectClas;
 %1$s ?object .

 VALUES ?subjectClass {%2$s}
}
GROUP BY ?subject
HAVING (?num > %3$s)
LIMIT 1