# Find a subject violating sh:in constaraint
# 0 - property
# 1 - subject's class
# 2 - an RDF list containg possible values

SELECT *
WHERE {
 ?subject a ?subjectClas;
 %1$s ?object .

 FILTER (?object NOT IN %3$s)
 VALUES ?subjectClass {%2$s}
}
LIMIT 1