PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
 ?subject a ?subjectClass;
 %1$s ?object .

 FILTER NOT EXISTS {?object rdf:type/rdfs:subClassOf*  %3$s}
 VALUES ?subjectClass {%2$s}
}
LIMIT 1