# Creates a file
#
# 0 - path
# 1 - size
# 2 - blobId
# 3 - creator

PREFIX fs: <http://fairspace.io/ontology#>

INSERT {
?iri a fs:File;
fs:filePath ?0;
fs:fileSize ?1;
fs:blobId ?2;
fs:createdBy ?3;
fs:dateCreated ?date;
fs:modifiedBy ?3;
fs:dateModified ?date . }
WHERE { BIND(IRI(CONCAT(STR(ws:), STRUUID())) as ?iri) BIND(NOW() as ?date) }