PREFIX fs: <http://fairspace.io/ontology#>
SELECT ?iri ?type ?path ?size
WHERE { ?iri fs:filePath ?path ; a ?type; fs:fileSize ?size;
FILTER(STRSTARTS(?path, ?param0) && !CONTAINS(SUBSTR(?path, STRLEN(?param0) + 1), '/')) }