# Moves a file from one location to another
# param0 - from
# param1 - to

PREFIX fs: <http://fairspace.io/ontology#>

INSERT { ?s ?p ?o } WHERE { ?s ?p ?o . ?s fs:filePath ?param0 };
INSERT { ?s fs:filePath ?param1 } WHERE {?s fs:filePath ?param0 };
DELETE WHERE { ?s fs:filePath ?param0 };

INSERT { ?s ?p ?o } WHERE { ?s ?p ?o . ?s fs:filePath ?path . FILTER(STRSTARTS(?path, CONCAT(?param0, '/'))) };
INSERT { ?s fs:filePath ?newPath}
WHERE {?s fs:filePath ?path . FILTER(STRSTARTS(?path, CONCAT(?param0, '/'))) BIND(CONCAT(?param1, '/', SUBSTR(?path, STRLEN(?param0) + 2)) as ?newPath) };
DELETE { ?s fs:filePath ?path } WHERE {?s fs:filePath ?path . FILTER(STRSTARTS(?path, CONCAT(?param0, '/')))}