# param0 - uri
# param1 - type
# param2 - path

PREFIX fs: <http://fairspace.io/ontology#>
INSERT { ?param0 a ?param1; fs:filePath ?param2 ; fs:fileSize 0; fs:dateCreated ?date; fs:dateModified ?date .}
WHERE { BIND(NOW() as ?date) }