# param0 - path
# param1 - size
# param2 - blob id
PREFIX fs: <http://fairspace.io/ontology#>
DELETE { ?s fs:fileSize ?x1 ; fs:blobId ?x2 .}
INSERT { ?s fs:fileSize ?param1; fs:blobId ?param2; fs:dateCreated ?date; fs:dateModified ?date }
WHERE { ?s fs:filePath ?param0 ; fs:fileSize ?x1 ; fs:blobId ?x2 . BIND(NOW() as ?date) }