# param0 - path
PREFIX fs: <http://fairspace.io/ontology#>
SELECT ?iri ?path ?type ?size ?created ?modified
WHERE { ?iri fs:filePath ?param0; a ?type; fs:fileSize ?size; fs:dateCreated ?created; fs:dateModified ?modified . BIND(?param0 as ?path) }