# Returns file info
# 0 - path
PREFIX fs: <http://fairspace.io/ontology#>

SELECT ?iri ?path ?isDirectory ?size ?created ?modified ?createdBy ?modifiedBy
WHERE { ?iri fs:filePath %1$s; fs:fileSize ?size; fs:dateCreated ?created; fs:dateModified ?modified; fs:createdBy ?createdBy; fs:modifiedBy ?modifiedBy.
BIND(%1$s as ?path)
BIND (EXISTS {?iri ?a fs:Directory} as ?isDirectory)
FILTER NOT EXISTS { ?iri fs:dateDeleted ?dateDeleted } }