# Returns all statements for a specific subject, rdf:List values and types for all refernced objects
# 0 - graph
# 1 - subject

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
  %2$s ?p ?o .
  ?o a ?type .
  ?listRest rdf:first ?head; rdf:rest ?tail .
  ?head a ?headType .

} WHERE {
  GRAPH %1$s {
    %2$s ?p ?o .
     OPTIONAL { ?o a ?type }
     OPTIONAL { ?o rdf:rest* ?listRest .
                ?listRest rdf:first ?head ;
                          rdf:rest ?tail .}
     OPTIONAL { ?head a ?headType}
  }
}
