# Find parent collection for a file or a directory
# 0 - list of files or directories

PREFIX fs: <http://fairspace.io/ontology#>

SELECT ?collection ?subject
WHERE {
  { ?subject a fs:Directory } UNION { ?subject a fs:File }
  ?subject fs:filePath ?filePath .
  ?collection a fs:Collection; fs:filePath ?collectionPath .


  FILTER(STRSTARTS(?filePath, CONCAT(?collectionPath, "/")))
  FILTER NOT EXISTS { ?collection fs:dateDeleted ?dateDeleted }
}
VALUES ?subject {%1$s}
