# Find parent collection for a file or a directory
# 0 - file or directory

PREFIX fs: <http://fairspace.io/ontology#>

SELECT ?collection
WHERE {
  ?collection a fs:Collection; fs:filePath ?collectionPath .
  %1$s fs:filePath ?filePath .
  FILTER(STRSTARTS(?filePath, CONCAT(?collectionPath, "/")))
  FILTER NOT EXISTS { ?collection fs:dateDeleted ?dateDeleted }
}