# 0 - path

PREFIX fs: <http://fairspace.io/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?iri
WHERE {
  ?iri fs:filePath ?0;
  FILTER NOT EXISTS { ?iri fs:dateDeleted ?dateDeleted }
}