# Checks whether an entity is machine only
#
# 0 - iri
# 1 - graph
# 2 - vocabulary

PREFIX fs: <http://fairspace.io/ontology#>
PREFIX sh: <http://www.w3.org/ns/shacl#>

ASK WHERE { GRAPH %2$s { %1$s a ?class } GRAPH %3$s {?shape sh:targetClass ?class; fs:machineOnly true . }}