# 0 - vocabulary graph

PREFIX fs: <http://fairspace.io/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {?s a rdf:Property; rdfs:label ?l}
WHERE {
    GRAPH ?0 { ?s a rdf:Property; fs:machineOnly true . }
    OPTIONAL { GRAPH ?0 {?s rdfs:label ?l} }
}
