# Get user's permission
# 0 - the resource
# 1 - the user

PREFIX fs: <http://fairspace.io/ontology#>

SELECT ?subject (IF(exists{ GRAPH ws:permissions {?subject fs:manage %2$s}},
                   fs:manage,
                 IF(exists{ GRAPH ws:permissions {?subject fs:write %2$s}},
                   fs:write,
                 IF(exists{ GRAPH ws:permissions {?subject fs:read %2$s}},
                   fs:read,
                 IF(exists{ GRAPH ws:permissions {?subject fs:writeRestricted true}},
                   fs:read,
                 IF(exists{?subject a fs:Collection},
                   fs:none,
                   fs:write))))) as ?access)
WHERE
{
  VALUES ?subject {%1$s}
}
