# Get user's permission
# 0 - the resource
# 1 - the user

PREFIX fs: <http://fairspace.io/ontology#>

SELECT * WHERE
{
  { GRAPH ws:permissions { ?subject ?access %2$s } }

  VALUES ?subject {%1$s}
}
