# Get user's permission
# 0 - the resource
# 1 - the user

PREFIX fs: <http://fairspace.io/ontology#>

SELECT * WHERE
{
  {
     { SELECT ?subject (fs:write as ?access) WHERE { ?subject ?p ?o ;   } }
     UNION
     { SELECT ?subject (fs:none as ?access) WHERE { ?subject a fs:Collection } }
     UNION
     { SELECT ?subject (fs:read as ?access) WHERE { GRAPH ws:permissions { ?subject fs:writeRestricted true } } }
     UNION
     { SELECT * WHERE { GRAPH ws:permissions { ?subject ?access %2$s } } }
  }

  VALUES ?subject {%1$s}
}
