# Select by mask
# 0 - graph
# 1 - subject
# 2 - predicate
# 3 - object

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
%2$s %3$s %4$s .
%4$s rdfs:label ?objectLabel . }
WHERE {
  GRAPH %1$s { %2$s %3$s %4$s }
  OPTIONAL { GRAPH %1$s  {%4$s rdfs:label ?objectLabel} }
}