# Select by mask
# 0 - subject
# 1 - predicate
# 2 - object

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
?0 ?1 ?2 ; rdfs:label ?subjectLabel .
?2 rdfs:label ?objectLabel . }
WHERE {
  { ?0 ?1 ?2 }
  OPTIONAL { ?0 rdfs:label ?subjectLabel }
  OPTIONAL { ?2 rdfs:label ?objectLabel }
}