# Select by mask
# 0 - graph
# 1 - subject
# 2 - predicate
# 3 - object
# 4 - vocabulary graph

PREFIX fs: <http://fairspace.io/ontology#>
PREFIX sh: <http://www.w3.org/ns/shacl#>

CONSTRUCT {
  %2$s %3$s %4$s .
  %4$s ?objectProperty ?objectLabel .
}
WHERE {
  GRAPH %1$s { %2$s %3$s %4$s }
  OPTIONAL { GRAPH %5$s { ?shape sh:path ?objectProperty ; fs:importantProperty true } }
  OPTIONAL { GRAPH %1$s  {%4$s ?objectProperty ?objectLabel} }
}
