# Select by mask
# 0 - graph
# 1 - subject
# 2 - predicate
# 3 - object

CONSTRUCT {
%2$s %3$s %4$s .
%4$s a ?objectType . }
WHERE {
  GRAPH %1$s { %2$s %3$s %4$s }
  OPTIONAL { GRAPH %1$s  {%4$s a ?objectType} }
}