# Marks an entity as deleted
#
# 0 - iri
# 1 - date deleted
# 2 - deletedBy
# 3 - target graph

PREFIX fs: <http://fairspace.io/ontology#>

INSERT DATA {
  GRAPH %4$s {
    %1$s fs:dateDeleted %2$s;
    fs:deletedBy %3$s;
  }
}

