# 0 - iri
# 1 - userName
# 2 - fullName
# 3 - authorities

PREFIX fs: <http://fairspace.io/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


DELETE {
  %1$s fs:userName ?oldUserName;
     rdfs:label ?oldFullName;
     fs:authorities ?oldAuthorities;
}
INSERT {
  %1$s fs:userName %2$s;
     rdfs:label %3$s;
     fs:authorities %4$s;
}
WHERE {
  %1$s a fs:User;
     fs:userName ?oldUserName;
     rdfs:label ?oldFullName;
     fs:authorities ?oldAuthorities;
}